/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package train;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

class records
{
   public int flag;
   public String brand_name,model_id,right_power,left_power,cost,extra;
}
public class addentry extends javax.swing.JFrame {
    
records rec[]=new records[10];

    /*
     * Creates new form addentry
     */
    public addentry() {
        initComponents();
        for(int i=0;i<10;i++)
        {
            rec[i]=new records();
        }
        try {
            File file = new File("F:\\add1.txt");
            Scanner reader=new Scanner(file);
            reader.useDelimiter(",");
            for(int i=0;i<10;i++)
            {
                rec[i].brand_name=reader.next();
                rec[i].model_id=reader.next();
                rec[i].right_power=reader.next();
                rec[i].left_power=reader.next();
                rec[i].cost=reader.next();
                rec[i].extra=reader.next();

            }

             for(int i=0;i<10;i++)
             {
                 if(!(rec[i].model_id.equals("EMPTY")))
                 rec[i].flag=1;
                 else
                 rec[i].flag=0;
             }
            
           
        } catch (FileNotFoundException ex) {
            Logger.getLogger(addentry.class.getName()).log(Level.SEVERE, null, ex);
        }
        //int p=3;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(660, 560));
        setPreferredSize(new java.awt.Dimension(660, 560));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel1.setText("BRAND NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 140, 180, 26);

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel2.setText("MODEL ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 180, 120, 26);

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel3.setText("RIGHT POWER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 220, 170, 26);

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel4.setText("LEFT POWER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 260, 150, 26);

        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel5.setText("COST");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 300, 150, 20);

        jButton1.setFont(new java.awt.Font("Lucida Handwriting", 1, 13)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 410, 120, 27);

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 140, 180, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 180, 180, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(240, 220, 180, 30);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(240, 260, 180, 30);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(240, 300, 180, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(390, 490, 230, 25);

        jButton2.setFont(new java.awt.Font("Lucida Handwriting", 1, 13)); // NOI18N
        jButton2.setText("GO BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 450, 120, 27);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/train/57c867ef020185461e036fb385de4cf0.jpg"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(660, 560));
        jLabel8.setMinimumSize(new java.awt.Dimension(660, 560));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1, -4, 660, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String bname,mid,rpwr,lpwr,cost;
        bname=jTextField1.getText();
        mid=jTextField2.getText();
        rpwr=jTextField3.getText();
        lpwr=jTextField4.getText();
        cost=jTextField5.getText();
        int p;
      //Random rand=new Random();  
   int r,q;
    r=Integer.parseInt(mid)%10;
   // q=rand.nextInt(1000)/10;
//std::cout<<q;
    q=Integer.parseInt(mid)/10;
    p=(q+r+7)%10; //because 7 is our fav number #CR7
    System.out.println("\n"+p);
    if(rec[p].flag==1)
   {
	    for(int i=p+1;i%10<10;i++)
	    {
		if(rec[i%10].flag==0)
               
                {
                    
                     p=i%10;
                      
                    break;
                }
            }
   }
  
     System.out.println("\n"+p);
     jLabel7.setText("ADDED SUCCESSFULLY!");

     rec[p].brand_name=bname;
     rec[p].model_id=mid;
     rec[p].right_power=rpwr;
     rec[p].left_power=lpwr;
     rec[p].cost=cost; 
     rec[p].extra="#";
     
     System.out.println(p);

    try {
        FileWriter fw=new FileWriter("F:\\add1.txt");
        for(int i=0;i<10;i++)
        {
        fw.write(rec[i].brand_name);
        fw.write(",");
        fw.write(rec[i].model_id);
        fw.write(",");
        fw.write(rec[i].right_power);
        fw.write(",");
        fw.write(rec[i].left_power);
        fw.write(",");
        fw.write(rec[i].cost);
        fw.write(",");
        fw.write("#");
        fw.write(",");
        fw.write("\n");
        }
        fw.close();
        
        
        
    } catch (IOException ex) {
        Logger.getLogger(addentry.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        

        
        
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    menupage mp=new menupage();
        mp.setVisible(true);    
        setVisible(false);// TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addentry().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
