/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package train;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Rachana
 */
public class deleteitem extends javax.swing.JFrame {

    /**
     * Creates new form deleteitem
     */
    public deleteitem() {
        initComponents();
    }


    /*private void delete(deleteitem.records5 reco) {
        throw new UnsupportedOperationException("Not supported yet."); 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    class records5
{
   public int flag;
   public String brand_name,model_id,right_power,left_power,cost,extra;
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 410));
        setPreferredSize(new java.awt.Dimension(640, 390));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel1.setText("MODEL ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(24, 44, 190, 31);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(232, 44, 176, 31);

        jButton1.setFont(new java.awt.Font("Lucida Handwriting", 1, 13)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(506, 42, 80, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 300, 230, 26);

        jButton2.setFont(new java.awt.Font("Lucida Handwriting", 1, 13)); // NOI18N
        jButton2.setText("GO BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 300, 110, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rachana\\Downloads\\8a2a95d79c4b66303ad7b611655acf86.jpg")); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(640, 410));
        jLabel4.setMinimumSize(new java.awt.Dimension(640, 410));
        jLabel4.setPreferredSize(new java.awt.Dimension(640, 390));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 640, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String bname,mid,rpwr,lpwr,cost;
        mid=jTextField1.getText();
        int flag=0;
        int p;
     
         int r,q;
    r=Integer.parseInt(mid)%10;
    

    q=Integer.parseInt(mid)/10;
    p=(q+r+7)%10; 
    
  
   String extra;
           records5 reco[]=new records5[10];
         for(int i=0;i<10;i++)
            reco[i]=new records5();

        try{
         
        Scanner rr=new Scanner(new File("F:\\add1.txt"));
        rr.useDelimiter(",");
        System.out.print(mid+"\n");
        
        for(int i=0;i<10;i++)
        {
        reco[i].brand_name=rr.next();
        reco[i].model_id=rr.next();
        reco[i].right_power=rr.next();
        reco[i].left_power=rr.next();
        reco[i].cost=rr.next();
        reco[i].extra=rr.next();
       
        
        }
        for(int i=0;i<10;i++)
        {
            
            if(mid.equals(reco[p].model_id)){
            
            reco[p].brand_name="EMPTY";
            reco[p].model_id="EMPTY";
            reco[p].right_power="EMPTY";
            reco[p].left_power="EMPTY";
            reco[p].cost="EMPTY";
            reco[p].extra="#";
            jLabel2.setText("ITEM DELETED!");
            System.out.print("\n"+p+"\t"+mid+"\t"+reco[p].model_id);
            
            flag = 1;
            break;
        }
              
        p++;
        if(p==10)
               p=0;
        }
         if(flag!=1) {
            jLabel2.setText("RECORD DOES NOT EXIST!");
        
        }
        
        System.out.println("\t"+flag);
        
        }
        
        catch(Exception e){}        // TODO add your handling code here:
        
         try {
        FileWriter fw=new FileWriter("F:\\add1.txt");
        for(int i=0;i<10;i++)
        {
        fw.write(reco[i].brand_name);
        fw.write(",");
        fw.write(reco[i].model_id);
        fw.write(",");
        fw.write(reco[i].right_power);
        fw.write(",");
        fw.write(reco[i].left_power);
        fw.write(",");
        fw.write(reco[i].cost);
        fw.write(",");
        fw.write("#");
        fw.write(",");
        fw.write("\n");
        }
        fw.close();
        
        
        
    } catch (IOException ex) {
        Logger.getLogger(addentry.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        menupage mp=new menupage();
        mp.setVisible(true); 
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteitem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
